import Model from "../assests/model.png";
import image_2 from "../assests/product-1.jpg";
import image_3 from "../assests/product-2.jpg";
import image_4 from "../assests/product-3.jpg";
export const data = [
  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_2,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_3,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_2,
    title: "This is  best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
];

export const data_1 = [
  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_3,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_2,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_2,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: Model,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: image_2,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: Model,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: image_2,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
];

export const data_2 = [
  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_2,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_3,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_2,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: Model,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: image_4,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: Model,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: image_4,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: Model,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: image_2,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: image_3,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: image_2,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
  {
    image: image_4,
    title: "This is our best product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 29990,
  },
];
export const Bridal = [
  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_2,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_3,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  }
];

export const Family = [
  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_2,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_3,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },

];

export const Makeup = [
  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },  {
    image: Model,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },

  {
    image: image_2,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_3,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 4000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },
  {
    image: image_4,
    title: "This is new product",
    rating: "4.9",
    review: 400,
    address: "jaipur rajastan",
    feature: "The Product Price is",
    price: 45000,
  },

];
